/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CONVERSOR.BASE64;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        
    }
}
